# Replace the text below to customize your site
site_name: Nicholas Niles
site_description: Portfolio
site_author: Nicholas Niles
copyright: Copyright 2022 Nicholas Niles - Creative Commons Attribution Non Commercial

site_url: https://nicholasniles.org

extra:
  # Set your own social media below (or remove)
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/

theme: 
  name: material
  palette:
    # Toggle light mode
    - scheme: slate
      favicon: test.svg
      primary: red 
      accent: deep purple
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      # Read more: https://timvink.github.io/mkdocs-git-revision-date-localized-plugin/options/#enabled
      enabled: !ENV [ENABLED_GIT_REVISION_DATE, False]

markdown_extensions:
  - extra
  - smarty
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
